# -*- coding: utf-8 -*-
"""Soal 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQxwqgwEXGDPhfKBen6oi3X7jT5rI2Pq
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class Diagnosis(KnowledgeEngine):
    @Rule(Fact(daun_berlubang=True))
    def ulat(self):
        print("Diagnosis: Kemungkinan tanaman dimakan Ulat.")

    @Rule(Fact(terdapat_bercak_hitam=True))
    def jamur(self):
        print("Diagnosis: Kemungkinan tanaman terkena Jamur.")

    @Rule(Fact(daun_menguning=True) & Fact(tanaman_layu=True))
    def virus(self):
        print("Diagnosis: Kemungkinan tanaman terkena Virus.")

    @Rule(Fact(daun_berlubang=False) & Fact(tanaman_layu=False) & Fact(daun_menguning=False) & Fact(terdapat_bercak_hitam=False))
    def tanaman_sehat(self):
        print("Diagnosis: Tanaman terlihat sehat.")

    @Rule(Fact(daun_menguning=True))
    def hama_kutu(self):
        print("Diagnosis: Kemungkinan tanaman terkena Hama Kutu.")

    @Rule(Fact(tanaman_layu=True))
    def bakteri(self):
        print("Diagnosis: Kemungkinan tanaman terkena Bakteri.")

def get_input():
    """Helper function to get user input as boolean (yes/no)."""
    def ask_question(question):
        return input(question + " (yes/no): ").strip().lower() == "yes"

    return {
        "daun_menguning": ask_question("Apakah pada daun menguning?"),
        "terdapat_bercak_hitam": ask_question("Apakah pada daun terdapat bercak hitam?"),
        "daun_berlubang": ask_question("Apakah pada daun berlubang?"),
        "tanaman_layu": ask_question("Apakah pada tanaman tersebut terlihat layu?"),
    }

if __name__ == "__main__":
    symptoms = get_input()
    engine = Diagnosis()
    engine.reset()  # Reset the knowledge engine

    for symptom, present in symptoms.items():
        engine.declare(Fact(**{symptom: present}))  # Declare facts
    engine.run()  # Run the inference engine